import geoJSON from '../assets/countries2.geo.json';

const allCountries = [
    {id:"1", name:"Aruba"},
    {id:"2", name:"Afghanistan"},
    {id:"3", name:"Angola"},
    {id:"4", name:"Anguilla"},
    {id:"5", name:"Albania"},
    {id:"6", name:"Aland"},
    {id:"7", name:"Andorra"},
    {id:"8", name:"United Arab Emirates"},
    {id:"9", name:"Argentina"},
    {id:"10", name:"Armenia"},
    {id:"11", name:"American Samoa"},
    {id:"12", name:"Antarctica"},
    {id:"13", name:"Ashmore and Cartier Islands"},
    {id:"14", name:"French Southern and Antarctic Lands"},
    {id:"15", name:"Antigua and Barbuda"},
    {id:"16", name:"Australia"},
    {id:"17", name:"Austria"},
    {id:"18", name:"Azerbaijan"},
    {id:"19", name:"Burundi"},
    {id:"20", name:"Belgium"},
    {id:"21", name:"Benin"},
    {id:"22", name:"Burkina Faso"},
    {id:"23", name:"Bangladesh"},
    {id:"24", name:"Bulgaria"},
    {id:"25", name:"Bahrain"},
    {id:"26", name:"The Bahamas"},
    {id:"27", name:"Bosnia and Herzegovina"},
    {id:"28", name:"Bajo Nuevo Bank (Petrel Is.)"},
    {id:"29", name:"Saint Barthelemy"},
    {id:"30", name:"Belarus"},
    {id:"31", name:"Belize"},
    {id:"255", name:"Bermuda"},
    {id:"32", name:"Bolivia"},
    {id:"33", name:"Brazil"},
    {id:"34", name:"Barbados"},
    {id:"35", name:"Brunei"},
    {id:"36", name:"Bhutan"},
    {id:"37", name:"Botswana"},
    {id:"38", name:"Central African Republic"},
    {id:"39", name:"Canada"},
    {id:"40", name:"Switzerland"},
    {id:"41", name:"Chile"},
    {id:"42", name:"China"},
    {id:"43", name:"Ivory Coast"},
    {id:"44", name:"Clipperton Island"},
    {id:"45", name:"Cameroon"},
    {id:"46", name:"Cyprus No Mans Area"},
    {id:"47", name:"Democratic Republic of the Congo"},
    {id:"48", name:"Republic of Congo"},
    {id:"49", name:"Cook Islands"},
    {id:"50", name:"Colombia"},
    {id:"51", name:"Comoros"},
    {id:"52", name:"Cape Verde"},
    {id:"53", name:"Costa Rica"},
    {id:"54", name:"Coral Sea Islands"},
    {id:"55", name:"Cuba"},
    {id:"56", name:"CuraÃ§ao"},
    {id:"57", name:"Cayman Islands"},
    {id:"58", name:"Northern Cyprus"},
    {id:"59", name:"Cyprus"},
    {id:"60", name:"Czech Republic"},
    {id:"61", name:"Germany"},
    {id:"62", name:"Djibouti"},
    {id:"63", name:"Dominica"},
    {id:"64", name:"Denmark"},
    {id:"65", name:"Dominican Republic"},
    {id:"66", name:"Algeria"},
    {id:"67", name:"Ecuador"},
    {id:"68", name:"Egypt"},
    {id:"69", name:"Eritrea"},
    {id:"70", name:"Dhekelia Sovereign Base Area"},
    {id:"71", name:"Spain"},
    {id:"72", name:"Estonia"},
    {id:"73", name:"Ethiopia"},
    {id:"74", name:"Finland"},
    {id:"75", name:"Fiji"},
    {id:"76", name:"Falkland Islands"},
    {id:"77", name:"France"},
    {id:"78", name:"Faroe Islands"},
    {id:"79", name:"Federated States of Micronesia"},
    {id:"80", name:"Gabon"},
    {id:"81", name:"United Kingdom"},
    {id:"82", name:"Georgia"},
    {id:"83", name:"Guernsey"},
    {id:"84", name:"Ghana"},
    {id:"85", name:"Gibraltar"},
    {id:"86", name:"Guinea"},
    {id:"87", name:"Gambia"},
    {id:"88", name:"Guinea Bissau"},
    {id:"89", name:"Equatorial Guinea"},
    {id:"90", name:"Greece"},
    {id:"91", name:"Grenada"},
    {id:"92", name:"Greenland"},
    {id:"93", name:"Guatemala"},
    {id:"94", name:"Guam"},
    {id:"95", name:"Guyana"},
    {id:"96", name:"Hong Kong S.A.R."},
    {id:"97", name:"Heard Island and McDonald Islands"},
    {id:"98", name:"Honduras"},
    {id:"99", name:"Croatia"},
    {id:"200", name:"Haiti"},
    {id:"101", name:"Hungary"},
    {id:"102", name:"Indonesia"},
    {id:"103", name:"Isle of Man"},
    {id:"104", name:"India"},
    {id:"105", name:"Indian Ocean Territories"},
    {id:"106", name:"British Indian Ocean Territory"},
    {id:"107", name:"Ireland"},
    {id:"108", name:"Iran"},
    {id:"109", name:"Iraq"},
    {id:"110", name:"Iceland"},
    {id:"111", name:"Israel"},
    {id:"112", name:"Italy"},
    {id:"113", name:"Jamaica"},
    {id:"114", name:"Jersey"},
    {id:"115", name:"Jordan"},
    {id:"116", name:"Japan"},
    {id:"117", name:"Baykonur Cosmodrome"},
    {id:"118", name:"Siachen Glacier"},
    {id:"119", name:"Kazakhstan"},
    {id:"120", name:"Kenya"},
    {id:"121", name:"Kyrgyzstan"},
    {id:"122", name:"Cambodia"},
    {id:"123", name:"Kiribati"},
    {id:"124", name:"Saint Kitts and Nevis"},
    {id:"125", name:"South Korea"},
    {id:"126", name:"Kosovo"},
    {id:"127", name:"Kuwait"},
    {id:"128", name:"Laos"},
    {id:"129", name:"Lebanon"},
    {id:"130", name:"Liberia"},
    {id:"131", name:"Libya"},
    {id:"132", name:"Saint Lucia"},
    {id:"133", name:"Liechtenstein"},
    {id:"134", name:"Sri Lanka"},
    {id:"135", name:"Lesotho"},
    {id:"136", name:"Lithuania"},
    {id:"137", name:"Luxembourg"},
    {id:"138", name:"Latvia"},
    {id:"139", name:"Macao S.A.R"},
    {id:"140", name:"Saint Martin"},
    {id:"141", name:"Morocco"},
    {id:"142", name:"Monaco"},
    {id:"143", name:"Moldova"},
    {id:"144", name:"Madagascar"},
    {id:"145", name:"Maldives"},
    {id:"146", name:"Mexico"},
    {id:"147", name:"Marshall Islands"},
    {id:"148", name:"Macedonia"},
    {id:"149", name:"Mali"},
    {id:"150", name:"Malta"},
    {id:"151", name:"Myanmar"},
    {id:"152", name:"Montenegro"},
    {id:"153", name:"Mongolia"},
    {id:"154", name:"Northern Mariana Islands"},
    {id:"155", name:"Mozambique"},
    {id:"156", name:"Mauritania"},
    {id:"157", name:"Montserrat"},
    {id:"158", name:"Mauritius"},
    {id:"159", name:"Malawi"},
    {id:"160", name:"Malaysia"},
    {id:"161", name:"Namibia"},
    {id:"162", name:"New Caledonia"},
    {id:"163", name:"Niger"},
    {id:"164", name:"Norfolk Island"},
    {id:"165", name:"Nigeria"},
    {id:"166", name:"Nicaragua"},
    {id:"167", name:"Niue"},
    {id:"168", name:"Netherlands"},
    {id:"169", name:"Norway"},
    {id:"170", name:"Nepal"},
    {id:"171", name:"Nauru"},
    {id:"172", name:"New Zealand"},
    {id:"173", name:"Oman"},
    {id:"174", name:"Pakistan"},
    {id:"175", name:"Panama"},
    {id:"176", name:"Pitcairn Islands"},
    {id:"177", name:"Peru"},
    {id:"178", name:"Spratly Islands"},
    {id:"179", name:"Philippines"},
    {id:"180", name:"Palau"},
    {id:"181", name:"Papua New Guinea"},
    {id:"182", name:"Poland"},
    {id:"183", name:"Puerto Rico"},
    {id:"184", name:"North Korea"},
    {id:"185", name:"Portugal"},
    {id:"186", name:"Paraguay"},
    {id:"187", name:"Palestine"},
    {id:"188", name:"French Polynesia"},
    {id:"189", name:"Qatar"},
    {id:"190", name:"Romania"},
    {id:"191", name:"Russia"},
    {id:"192", name:"Rwanda"},
    {id:"193", name:"Western Sahara"},
    {id:"194", name:"Saudi Arabia"},
    {id:"195", name:"Scarborough Reef"},
    {id:"196", name:"Sudan"},
    {id:"197", name:"South Sudan"},
    {id:"198", name:"Senegal"},
    {id:"199", name:"Serranilla Bank"},
    {id:"200", name:"Singapore"},
    {id:"201", name:"South Georgia and South Sandwich Islands"},
    {id:"202", name:"Saint Helena"},
    {id:"203", name:"Solomon Islands"},
    {id:"204", name:"Sierra Leone"},
    {id:"205", name:"El Salvador"},
    {id:"206", name:"San Marino"},
    {id:"207", name:"Somaliland"},
    {id:"208", name:"Somalia"},
    {id:"209", name:"Saint Pierre and Miquelon"},
    {id:"210", name:"Republic of Serbia"},
    {id:"211", name:"Sao Tome and Principe"},
    {id:"212", name:"Suriname"},
    {id:"213", name:"Slovakia"},
    {id:"214", name:"Slovenia"},
    {id:"215", name:"Sweden"},
    {id:"216", name:"Swaziland"},
    {id:"217", name:"Sint Maarten"},
    {id:"218", name:"Seychelles"},
    {id:"219", name:"Syria"},
    {id:"220", name:"Turks and Caicos Islands"},
    {id:"221", name:"Chad"},
    {id:"222", name:"Togo"},
    {id:"223", name:"Thailand"},
    {id:"224", name:"Tajikistan"},
    {id:"225", name:"Turkmenistan"},
    {id:"226", name:"East Timor"},
    {id:"227", name:"Tonga"},
    {id:"228", name:"Trinidad and Tobago"},
    {id:"229", name:"Tunisia"},
    {id:"230", name:"Turkey"},
    {id:"231", name:"Tuvalu"},
    {id:"232", name:"Taiwan"},
    {id:"233", name:"United Republic of Tanzania"},
    {id:"234", name:"Uganda"},
    {id:"235", name:"Ukraine"},
    {id:"236", name:"United States Minor Outlying Islands"},
    {id:"237", name:"Uruguay"},
    {id:"238", name:"United States of America"},
    {id:"239", name:"US Naval Base Guantanamo Bay"},
    {id:"240", name:"Uzbekistan"},
    {id:"241", name:"Vatican"},
    {id:"242", name:"Saint Vincent and the Grenadines"},
    {id:"243", name:"Venezuela"},
    {id:"244", name:"British Virgin Islands"},
    {id:"245", name:"United States Virgin Islands"},
    {id:"246", name:"Vietnam"},
    {id:"247", name:"Vanuatu"},
    {id:"248", name:"Wallis and Futuna"},
    {id:"249", name:"Akrotiri Sovereign Base Area"},
    {id:"250", name:"Samoa"},
    {id:"251", name:"Yemen"},
    {id:"252", name:"South Africa"},
    {id:"253", name:"Zambia"},
    {id:"254", name:"Zimbabwe"}                                                         
    ];
    const mainCountries = [
      { id: "2", name: "Afghanistan" },
      { id: "5", name: "Albania" },
      { id: "66", name: "Algeria" },
      { id: "3", name: "Angola" },
      { id: "9", name: "Argentina" },
      { id: "0", name: "Armenia" },
      { id: "6", name: "Australia" },
      { id: "7", name: "Austria" },
      { id: "8", name: "Azerbaijan" },
      { id: "23", name: "Bangladesh" },
      { id: "30", name: "Belarus" },
      { id: "20", name: "Belgium" },
      { id: "21", name: "Benin" },
      { id: "32", name: "Bolivia" },
      { id: "27", name: "Bosnia and Herzegovina" },
      { id: "37", name: "Botswana" },
      { id: "33", name: "Brazil" },
      { id: "24", name: "Bulgaria" },
      { id: "22", name: "Burkina Faso" },
      { id: "19", name: "Burundi" },
      { id: "122", name: "Cambodia" },
      { id: "45", name: "Cameroon" },
      { id: "39", name: "Canada" },
      { id: "38", name: "Central African Republic" },
      { id: "221", name: "Chad" },
      { id: "41", name: "Chile" },
      { id: "42", name: "China" },
      { id: "50", name: "Colombia" },
      { id: "47", name: "Democratic Republic of the Congo" },
      { id: "48", name: "Republic of Congo" },
      { id: "53", name: "Costa Rica" },
      { id: "99", name: "Croatia" },
      { id: "55", name: "Cuba" },
      { id: "59", name: "Cyprus" },
      { id: "60", name: "Czech Republic" },
      { id: "64", name: "Denmark" },
      { id: "65", name: "Dominican Republic" },
      { id: "67", name: "Ecuador" },
      { id: "68", name: "Egypt" },
      { id: "205", name: "El Salvador" },
      { id: "72", name: "Estonia" },
      { id: "73", name: "Ethiopia" },
      { id: "74", name: "Finland" },
      { id: "77", name: "France" },
      { id: "82", name: "Georgia" },
      { id: "61", name: "Germany" },
      { id: "84", name: "Ghana" },
      { id: "90", name: "Greece" },
      { id: "93", name: "Guatemala" },
      { id: "98", name: "Honduras" },
      { id: "101", name: "Hungary" },
      { id: "110", name: "Iceland" },
      { id: "104", name: "India" },
      { id: "102", name: "Indonesia" },
      { id: "108", name: "Iran" },
      { id: "109", name: "Iraq" },
      { id: "107", name: "Ireland" },
      { id: "111", name: "Israel" },
      { id: "112", name: "Italy" },
      { id: "43", name: "Ivory Coast" },
      { id: "113", name: "Jamaica" },
      { id: "116", name: "Japan" },
      { id: "115", name: "Jordan" },
      { id: "119", name: "Kazakhstan" },
      { id: "120", name: "Kenya" },
      { id: "127", name: "Kuwait" },
      { id: "121", name: "Kyrgyzstan" },
      { id: "128", name: "Laos" },
      { id: "138", name: "Latvia" },
      { id: "129", name: "Lebanon" },
      { id: "136", name: "Lithuania" },
      { id: "137", name: "Luxembourg" },
      { id: "144", name: "Madagascar" },
      { id: "159", name: "Malawi" },
      { id: "160", name: "Malaysia" },
      { id: "149", name: "Mali" },
      { id: "150", name: "Malta" },
      { id: "146", name: "Mexico" },
      { id: "143", name: "Moldova" },
      { id: "153", name: "Mongolia" },
      { id: "141", name: "Morocco" },
      { id: "155", name: "Mozambique" },
      { id: "151", name: "Myanmar" },
      { id: "161", name: "Namibia" },
      { id: "170", name: "Nepal" },
      { id: "168", name: "Netherlands" },
      { id: "172", name: "New Zealand" },
      { id: "166", name: "Nicaragua" },
      { id: "163", name: "Niger" },
      { id: "165", name: "Nigeria" },
      { id: "184", name: "North Korea" },
      { id: "169", name: "Norway" },
      { id: "173", name: "Oman" },
      { id: "174", name: "Pakistan" },
      { id: "175", name: "Panama" },
      { id: "181", name: "Papua New Guinea" },
      { id: "186", name: "Paraguay" },
      { id: "177", name: "Peru" },
      { id: "179", name: "Philippines" },
      { id: "182", name: "Poland" },
      { id: "185", name: "Portugal" },
      { id: "189", name: "Qatar" },
      { id: "190", name: "Romania" },
      { id: "191", name: "Russia" },
      { id: "192", name: "Rwanda" },
      { id: "194", name: "Saudi Arabia" },
      { id: "198", name: "Senegal" },
      { id: "210", name: "Republic of Serbia" },
      { id: "204", name: "Sierra Leone" },
      { id: "200", name: "Singapore" },
      { id: "213", name: "Slovakia" },
      { id: "214", name: "Slovenia" },
      { id: "208", name: "Somalia" },
      { id: "252", name: "South Africa" },
      { id: "125", name: "South Korea" },
      { id: "219", name: "Syria" },
      { id: "224", name: "Tajikistan" },
      { id: "233", name: "United Republic of Tanzania" },
      { id: "223", name: "Thailand" },
      { id: "222", name: "Togo" },
      { id: "228", name: "Trinidad and Tobago" },
      { id: "229", name: "Tunisia" },
      { id: "230", name: "Turkey" },
      { id: "225", name: "Turkmenistan" },
      { id: "234", name: "Uganda" },
      { id: "235", name: "Ukraine" },
      { id: "8", name: "United Arab Emirates" },
      { id: "81", name: "United Kingdom" },
      { id: "238", name: "United States of America" },
      { id: "237", name: "Uruguay" },
      { id: "240", name: "Uzbekistan" },
      { id: "243", name: "Venezuela" },
      { id: "246", name: "Vietnam" },
      { id: "251", name: "Yemen" },
      { id: "253", name: "Zambia" },
      { id: "254", name: "Zimbabwe" }
  ];
  
  const mainCountriesEnglish = [
    { id: "2", name: "Afghanistan", capital: "Kabul", alpha2: "AF" },
    { id: "5", name: "Albania", capital: "Tirana", alpha2: "AL" },
    { id: "66", name: "Algeria", capital: "Algiers", alpha2: "DZ" },
    { id: "3", name: "Angola", capital: "Luanda", alpha2: "AO" },
    { id: "9", name: "Argentina", capital: "Buenos Aires", alpha2: "AR" },
    { id: "10", name: "Armenia", capital: "Yerevan", alpha2: "AM" },
    { id: "16", name: "Australia", capital: "Canberra", alpha2: "AU" },
    { id: "17", name: "Austria", capital: "Vienna", alpha2: "AT" },
    { id: "18", name: "Azerbaijan", capital: "Baku", alpha2: "AZ" },
    { id: "23", name: "Bangladesh", capital: "Dhaka", alpha2: "BD" },
    { id: "30", name: "Belarus", capital: "Minsk", alpha2: "BY" },
    { id: "20", name: "Belgium", capital: "Brussels", alpha2: "BE" },
    { id: "21", name: "Benin", capital: "Porto-Novo", alpha2: "BJ" },
    { id: "32", name: "Bolivia", capital: "Sucre", alpha2: "BO" },
    { id: "27", name: "Bosnia and Herzegovina", capital: "Sarajevo", alpha2: "BA" },
    { id: "37", name: "Botswana", capital: "Gaborone", alpha2: "BW" },
    { id: "33", name: "Brazil", capital: "Brasilia", alpha2: "BR" },
    { id: "24", name: "Bulgaria", capital: "Sofia", alpha2: "BG" },
    { id: "22", name: "Burkina Faso", capital: "Ouagadougou", alpha2: "BF" },
    { id: "19", name: "Burundi", capital: "Gitega", alpha2: "BI" },
    { id: "122", name: "Cambodia", capital: "Phnom Penh", alpha2: "KH" },
    { id: "45", name: "Cameroon", capital: "Yaoundé", alpha2: "CM" },
    { id: "39", name: "Canada", capital: "Ottawa", alpha2: "CA" },
    { id: "38", name: "Central African Republic", capital: "Bangui", alpha2: "CF" },
    { id: "221", name: "Chad", capital: "N'Djamena", alpha2: "TD" },
    { id: "41", name: "Chile", capital: "Santiago", alpha2: "CL" },
    { id: "42", name: "China", capital: "Beijing", alpha2: "CN" },
    { id: "50", name: "Colombia", capital: "Bogotá", alpha2: "CO" },
    { id: "47", name: "Democratic Republic of the Congo", capital: "Kinshasa", alpha2: "CD" },
    { id: "48", name: "Republic of the Congo", capital: "Brazzaville", alpha2: "CG" },
    { id: "53", name: "Costa Rica", capital: "San José", alpha2: "CR" },
    { id: "99", name: "Croatia", capital: "Zagreb", alpha2: "HR" },
    { id: "55", name: "Cuba", capital: "Havana", alpha2: "CU" },
    { id: "59", name: "Cyprus", capital: "Nicosia", alpha2: "CY" },
    { id: "60", name: "Czech Republic", capital: "Prague", alpha2: "CZ" },
    { id: "64", name: "Denmark", capital: "Copenhagen", alpha2: "DK" },
    { id: "65", name: "Dominican Republic", capital: "Santo Domingo", alpha2: "DO" },
    { id: "67", name: "Ecuador", capital: "Quito", alpha2: "EC" },
    { id: "68", name: "Egypt", capital: "Cairo", alpha2: "EG" },
    { id: "205", name: "El Salvador", capital: "San Salvador", alpha2: "SV" },
    { id: "72", name: "Estonia", capital: "Tallinn", alpha2: "EE" },
    { id: "73", name: "Ethiopia", capital: "Addis Ababa", alpha2: "ET" },
    { id: "74", name: "Finland", capital: "Helsinki", alpha2: "FI" },
    { id: "77", name: "France", capital: "Paris", alpha2: "FR" },
    { id: "82", name: "Georgia", capital: "Tbilisi", alpha2: "GE" },
    { id: "61", name: "Germany", capital: "Berlin", alpha2: "DE" },
    { id: "84", name: "Ghana", capital: "Accra", alpha2: "GH" },
    { id: "90", name: "Greece", capital: "Athens", alpha2: "GR" },
    { id: "93", name: "Guatemala", capital: "Guatemala City", alpha2: "GT" },
    { id: "98", name: "Honduras", capital: "Tegucigalpa", alpha2: "HN" },
    { id: "101", name: "Hungary", capital: "Budapest", alpha2: "HU" },
    { id: "110", name: "Iceland", capital: "Reykjavik", alpha2: "IS" },
    { id: "104", name: "India", capital: "New Delhi", alpha2: "IN" },
    { id: "102", name: "Indonesia", capital: "Jakarta", alpha2: "ID" },
    { id: "108", name: "Iran", capital: "Tehran", alpha2: "IR" },
    { id: "109", name: "Iraq", capital: "Baghdad", alpha2: "IQ" },
    { id: "107", name: "Ireland", capital: "Dublin", alpha2: "IE" },
    { id: "111", name: "Israel", capital: "Jerusalem", alpha2: "IL" },
    { id: "112", name: "Italy", capital: "Rome", alpha2: "IT" },
    { id: "43", name: "Ivory Coast", capital: "Yamoussoukro", alpha2: "CI" },
    { id: "113", name: "Jamaica", capital: "Kingston", alpha2: "JM" },
    { id: "116", name: "Japan", capital: "Tokyo", alpha2: "JP" },
    { id: "115", name: "Jordan", capital: "Amman", alpha2: "JO" },
    { id: "119", name: "Kazakhstan", capital: "Astana", alpha2: "KZ" },
    { id: "120", name: "Kenya", capital: "Nairobi", alpha2: "KE" },
    { id: "127", name: "Kuwait", capital: "Kuwait City", alpha2: "KW" },
    { id: "121", name: "Kyrgyzstan", capital: "Bishkek", alpha2: "KG" },
    { id: "128", name: "Laos", capital: "Vientiane", alpha2: "LA" },
    { id: "138", name: "Latvia", capital: "Riga", alpha2: "LV" },
    { id: "129", name: "Lebanon", capital: "Beirut", alpha2: "LB" },
    { id: "136", name: "Lithuania", capital: "Vilnius", alpha2: "LT" },
    { id: "137", name: "Luxembourg", capital: "Luxembourg City", alpha2: "LU" },
    { id: "144", name: "Madagascar", capital: "Antananarivo", alpha2: "MG" },
    { id: "159", name: "Malawi", capital: "Lilongwe", alpha2: "MW" },
    { id: "160", name: "Malaysia", capital: "Kuala Lumpur", alpha2: "MY" },
    { id: "149", name: "Mali", capital: "Bamako", alpha2: "ML" },
    { id: "150", name: "Malta", capital: "Valletta", alpha2: "MT" },
    { id: "156", name: "Mauritania", capital: "Nouakchott", alpha2: "MR" },
    { id: "146", name: "Mexico", capital: "Mexico City", alpha2: "MX" },
    { id: "143", name: "Moldova", capital: "Chisinau", alpha2: "MD" },
    { id: "153", name: "Mongolia", capital: "Ulaanbaatar", alpha2: "MN" },
    { id: "152", name: "Montenegro", capital: "Podgorica", alpha2: "ME" },
    { id: "141", name: "Morocco", capital: "Rabat", alpha2: "MA" },
    { id: "155", name: "Mozambique", capital: "Maputo", alpha2: "MZ" },
    { id: "151", name: "Myanmar", capital: "Naypyidaw", alpha2: "MM" },
    { id: "161", name: "Namibia", capital: "Windhoek", alpha2: "NA" },
    { id: "170", name: "Nepal", capital: "Kathmandu", alpha2: "NP" },
    { id: "168", name: "Netherlands", capital: "Amsterdam", alpha2: "NL" },
    { id: "172", name: "New Zealand", capital: "Wellington", alpha2: "NZ" },
    { id: "166", name: "Nicaragua", capital: "Managua", alpha2: "NI" },
    { id: "163", name: "Niger", capital: "Niamey", alpha2: "NE" },
    { id: "165", name: "Nigeria", capital: "Abuja", alpha2: "NG" },
    { id: "184", name: "North Korea", capital: "Pyongyang", alpha2: "KP" },
    { id: "169", name: "Norway", capital: "Oslo", alpha2: "NO" },
    { id: "174", name: "Pakistan", capital: "Islamabad", alpha2: "PK" },
    { id: "175", name: "Panama", capital: "Panama City", alpha2: "PA" },
    { id: "181", name: "Papua New Guinea", capital: "Port Moresby", alpha2: "PG" },
    { id: "186", name: "Paraguay", capital: "Asuncion", alpha2: "PY" },
    { id: "177", name: "Peru", capital: "Lima", alpha2: "PE" },
    { id: "179", name: "Philippines", capital: "Manila", alpha2: "PH" },
    { id: "182", name: "Poland", capital: "Warsaw", alpha2: "PL" },
    { id: "185", name: "Portugal", capital: "Lisbon", alpha2: "PT" },
    { id: "189", name: "Qatar", capital: "Doha", alpha2: "QA" },
    { id: "190", name: "Romania", capital: "Bucharest", alpha2: "RO" },
    { id: "191", name: "Russia", capital: "Moscow", alpha2: "RU" },
    { id: "192", name: "Rwanda", capital: "Kigali", alpha2: "RW" },
    { id: "194", name: "Saudi Arabia", capital: "Riyadh", alpha2: "SA" },
    { id: "198", name: "Senegal", capital: "Dakar", alpha2: "SN" },
    { id: "210", name: "Serbia", capital: "Belgrade", alpha2: "RS" },
    { id: "204", name: "Sierra Leone", capital: "Freetown", alpha2: "SL" },
    { id: "200", name: "Singapore", capital: "Singapore", alpha2: "SG" },
    { id: "213", name: "Slovakia", capital: "Bratislava", alpha2: "SK" },
    { id: "214", name: "Slovenia", capital: "Ljubljana", alpha2: "SI" },
    { id: "208", name: "Somalia", capital: "Mogadishu", alpha2: "SO" },
    { id: "252", name: "South Africa", capital: "Pretoria", alpha2: "ZA" },
    { id: "125", name: "South Korea", capital: "Seoul", alpha2: "KR" },
    { id: "197", name: "South Sudan", capital: "Juba", alpha2: "SS" },
    { id: "71", name: "Spain", capital: "Madrid", alpha2: "ES" },
    { id: "134", name: "Sri Lanka", capital: "Sri Jayawardenepura Kotte", alpha2: "LK" },
    { id: "196", name: "Sudan", capital: "Khartoum", alpha2: "SD" },
    { id: "215", name: "Sweden", capital: "Stockholm", alpha2: "SE" },
    { id: "40", name: "Switzerland", capital: "Bern", alpha2: "CH" },
    { id: "219", name: "Syria", capital: "Damascus", alpha2: "SY" },
    { id: "224", name: "Tajikistan", capital: "Dushanbe", alpha2: "TJ" },
    { id: "233", name: "Tanzania", capital: "Dodoma", alpha2: "TZ" },
    { id: "223", name: "Thailand", capital: "Bangkok", alpha2: "TH" },
    { id: "222", name: "Togo", capital: "Lome", alpha2: "TG" },
    { id: "228", name: "Trinidad and Tobago", capital: "Port of Spain", alpha2: "TT" },
    { id: "229", name: "Tunisia", capital: "Tunis", alpha2: "TN" },
    { id: "230", name: "Turkey", capital: "Ankara", alpha2: "TR" },
    { id: "225", name: "Turkmenistan", capital: "Ashgabat", alpha2: "TM" },
    { id: "234", name: "Uganda", capital: "Kampala", alpha2: "UG" },
    { id: "235", name: "Ukraine", capital: "Kyiv", alpha2: "UA" },
    { id: "8", name: "United Arab Emirates", capital: "Abu Dhabi", alpha2: "AE" },
    { id: "81", name: "United Kingdom", capital: "London", alpha2: "GB" },
    { id: "238", name: "United States", capital: "Washington D.C.", alpha2: "US" },
    { id: "237", name: "Uruguay", capital: "Montevideo", alpha2: "UY" },
    { id: "240", name: "Uzbekistan", capital: "Tashkent", alpha2: "UZ" },
    { id: "243", name: "Venezuela", capital: "Caracas", alpha2: "VE" },
    { id: "246", name: "Vietnam", capital: "Hanoi", alpha2: "VN" },
    { id: "253", name: "Zambia", capital: "Lusaka", alpha2: "ZM" },
    { id: "254", name: "Zimbabwe", capital: "Harare", alpha2: "ZW" }
];

const getPolygonCenter = (coordinates) => {
  let total = [0, 0];
  let count = 0;
  
  coordinates.forEach(polygon => {
    polygon[0].forEach(coord => {
      total[0] += coord[0];
      total[1] += coord[1];
      count++;
    });
  });
  
  return [total[0] / count, total[1] / count];
};

const CountryList = ({ count, mainOnly = false}) => {
    const shuffleArray = array => {
      for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
      }
      return array;
    };

    // Select and suffle the countries
    let selectedCountries = shuffleArray(mainOnly ? mainCountriesEnglish : allCountries).slice(0, count);

    // Eliminates duplicates
    selectedCountries = [...new Set(selectedCountries.map(country => country.name))].map(name => selectedCountries.find(country => country.name === name));


    return selectedCountries;  // Return the array of selected countries
};

// Function to obtain the center of a country by its id
export const getCountryCenterById = (countryId) => {
  const feature = geoJSON.features.find(feature => feature.id.toString() === countryId.toString());
  if (feature) {
    return getPolygonCenter(feature.geometry.coordinates);
  }
  return null;
};

export default CountryList;